### ISSUE TITLE
I am getting an error with IDA9 - 

### ISSUE THREAD

**Issue by karpiyon** [LAC-Japan/IDA_Plugin_AntiDebugSeeker#2]
On line 659:
        start_addr = idaapi.cvar.inf.min_ea
        end_addr = idaapi.cvar.inf.max_ea

I don't think IDA 9 had this object:
 idaapi.cvar.inf.min_ea or  idaapi.cvar.inf.max_ea

need o replace it with:
```
import ida-ida
...
        start_addr = ida_ida.inf_get_max_ea()
        end_addr = ida_ida.inf_get_min_ea()
        
```

**Comment by takatake-code** [comment]
Thank you for the information and for providing the correction code. 
Please continue to contact me if you have any errors or requests.

This issue has been resolved.
